-- Migration: 002_update_keygen.sql
-- Documents the new HMAC-signed key format introduced in the application layer.
--
-- Key format overview
-- ─────────────────────────────────────────────────────────────────────────────
-- Legacy keys (still supported):
--   as_pro_<random>        — generated by the original SQL generate_license_key()
--   as_team_<random>
--   as_enterprise_<random>
--
-- New keys (preferred for all new provisioning):
--   asv1_<base64url-payload>.<base64url-hmac-signature>
--
--   The payload is a JSON object signed with HMAC-SHA256 using the secret in
--   AGENTSENTINEL_LICENSE_SIGNING_SECRET.  These keys can be verified OFFLINE
--   by the SDK without a network round-trip, and can also be looked up in the
--   licenses table when they have been provisioned there.
--
--   HMAC signing MUST happen in the application layer (Python SDK or a trusted
--   server), not inside SQL, because the signing secret must never be stored in
--   the database.
--
-- The validate-license Edge Function accepts both formats via a plain
-- license_key equality lookup against the licenses table, so no database schema
-- change is required — just insert new asv1_* keys using the same column.
-- ─────────────────────────────────────────────────────────────────────────────

-- Update the comment on the existing generate_license_key SQL function to note
-- that new code should use the application-layer keygen instead.
COMMENT ON FUNCTION generate_license_key(text) IS
  'Generates a legacy as_<tier>_<random> key for backward compatibility. '
  'New provisioning should use the Python agentsentinel.utils.keygen module '
  'which produces HMAC-signed asv1_* keys that support offline verification.';
